name: Publish Listeners

on:
  push:
    branches: [ dev, main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            elementpay/epay-listeners:latest
            elementpay/epay-listeners:${{ github.ref_name }}
      - name: Dispatch deploy event to infra
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.INFRA_PAT }}
          repository: elementpayHQ/infra
          event-type: deploy
          client-payload: '{"ref":"${{ github.ref_name }}"}'
